version: '3.1'
services:
  stats-client:
    build: ./stats/stats-client
    image: stats-client
    container_name: stats-client
    ports:
      - "9090:9090"
    depends_on:
      - stats-server
    volumes:
      - /usr/share/zoneinfo/Europe:/usr/share/zoneinfo/Europe:ro
    environment:
      - STATS_SERVER_URL=http://stats-server:8080
  stats-server:
    build: ./stats/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "8081:8080"
    depends_on:
      - stats-db
    volumes:
      - /usr/share/zoneinfo/Europe:/usr/share/zoneinfo/Europe:ro
    environment:
      - DB_NAME=Stats
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=purrrrrr
      - DB_HOST=stats-db
      - DB_PORT=5432

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    volumes:
      - /usr/share/zoneinfo/Europe:/usr/share/zoneinfo/Europe:ro
    environment:
      - POSTGRES_DB=Stats
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=purrrrrr

  main-service:
    build: ./main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - service-db
    volumes:
      - /usr/share/zoneinfo/Europe:/usr/share/zoneinfo/Europe:ro
    environment:
      - STATS_SERVER_URL=http://stats-client:9090
      - DB_NAME=service
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=purrrrrr
      - DB_HOST=service-db
      - DB_PORT=5432

  service-db:
    image: postgres:14-alpine
    container_name: service-db
    ports:
      - "6542:5432"
    volumes:
      - /usr/share/zoneinfo/Europe:/usr/share/zoneinfo/Europe:ro
    environment:
      - POSTGRES_DB=service
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=purrrrrr