DROP TABLE IF EXISTS Events CASCADE;

CREATE TABLE IF NOT EXISTS Events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app varchar(50) NOT NULL,
    uri varchar(255) NOT NULL,
    ip varchar(20) NOT NULL,
    date_request timestamp,
    UNIQUE (id)
);


